### ISSUE TITLE
¿Es necesario agregar temas sobre criptografia y hashing?

### ISSUE THREAD

**Issue by idcmardelplata** [idcmardelplata/Blockchain-Technology#5]
# ¿Creen que sea necesario agregar material relacionado con la criptografia y temas de hashing?.

Pregunto esto porque esa es la base de la blockchain, si quieren puedo subir material relacionado a:
  * Cifrado simetrico
  * Cifrado asimetrico
  * Cifrado de curva eliptica
  * Encriptacion
  * Firma digital
  * Certificados etc etc...

Si les parece que puede ser util, avisenme y subo material sobre el tema.

**Comment by Zlatkowicz** [comment]
Yo creo que conceptos como criptográfica asimétrica, firma digital y hash son conceptos que todos deberían entender o por lo menos tener de oído si quieren meterse a este ecosistema. 

Tarde o temprano los van a tener que investigar. Así que yo diría que sí

**Comment by idcmardelplata** [comment]
Un poco tarde lei la respuesta, voy a subir ese material entonces.

**Comment by idcmardelplata** [comment]
Ok,si bien lei y poco tarde el comentario voy a subir material y otro lo voy a preparar desde cero ya que creo que en un par de videos esos temas pueden quedar bien explicados y asi evitamos que se tengan que leer varias paginas sobre el tema.
