### ISSUE TITLE
Agregar apartado con listado de blockchains 

### ISSUE THREAD

**Issue by ferbarraza99** [idcmardelplata/Blockchain-Technology#6]
Estaría bueno agregar un listado de blockchains, protocolos o tecnologías similares de interés, con su nombre y un link hacia alguna pagina oficial o paper.
Pueden ser tanto conocidas como poco conocidas. Ejemplo: 
Rchaing: https://rchain.coop/
Firo: https://firo.org/
Iota: https://www.iota.org/
Solana: https://solana.com/
Cosmos: https://cosmos.network/
Stellar: https://www.stellar.org/
Loopring: https://loopring.org/

**Comment by idcmardelplata** [comment]
Me parece fantastico, ahi agrego estas que pasaste al readme.

Eso nos va a venir genial para poder ampliar un poco mas la vision sobre
lo que se puede y no hacer mediante la blockchain y como podemos combinar 
protocolos y proyectos juntos para poder construir sobre ellos.

Mil gracias por el aporte fer! :)
