### ISSUE TITLE
Notion de conceptos básicos (Solidity) 📖

### ISSUE THREAD

**Issue by Zlatkowicz** [idcmardelplata/Blockchain-Technology#7]
Acabo de crear un **_Notion_** donde tomo nota de todos los conceptos que voy escuchando sobre **Solidity**. Si quieren editar el **_Notion_**, mándenme un mensaje al WhatsApp y lo vemos! 🦾

**_Notion_**: https://tall-tower-32e.notion.site/Introducci-n-a-Solidity-d330eaa381ac44a58f80175d0dbc21ea

**Comment by idcmardelplata** [comment]
Super útil, ya esta agregado al README.md, gracias por la ayuda! :100:
